### ISSUE TITLE
Race condition in tests causes failure due to duplicated TelechatDate

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5173]
### Describe the issue

The test `ietf.secr.telechat.tests.SecrTelechatTestCase.test_bash` sometimes fails due to multiple `TelechatDate` instances existing for "today":

```
======================================================================
ERROR: test_bash (ietf.secr.telechat.tests.SecrTelechatTestCase.test_bash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/secr/telechat/tests.py", line 146, in test_bash
    response = self.client.get(url)
  File "/usr/local/lib/python3.9/site-packages/django/test/client.py", line 535, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/usr/local/lib/python3.9/site-packages/django/test/client.py", line 345, in get
    return self.generic('GET', path, secure=secure, **{
  File "/usr/local/lib/python3.9/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.9/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/__w/datatracker/datatracker/ietf/ietfauth/utils.py", line 121, in inner
    return view_func(request, *args, **kwargs)
  File "/__w/datatracker/datatracker/ietf/secr/telechat/views.py", line 146, in bash
    agenda = agenda_data(date=date)
  File "/__w/datatracker/datatracker/ietf/iesg/agenda.py", line 218, in agenda_data
    date = get_agenda_date(date)
  File "/__w/datatracker/datatracker/ietf/iesg/agenda.py", line 31, in get_agenda_date
    return TelechatDate.objects.active().get(date=parsed_date).date
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 410, in get
    raise self.model.MultipleObjectsReturned(
ietf.iesg.models.TelechatDate.MultipleObjectsReturned: get() returned more than one TelechatDate -- it returned 2!

======================================================================
```
 (see https://github.com/ietf-tools/datatracker/actions/runs/4221171330/jobs/7328154474)

This happens because the test fixtures in settings.py include ietf.utils.test_data.make_immutable_test_data() for every test. That fixture sets up TelechatDate instances that includes "tomorrow". If you run it very near midnight in settings.TIME_ZONE, then that might be "today" when you actually run your test. The test then creates its own TelechatDate for "today," which leads to there being two instead of one.

It'd be easy to fix the tests only to create a TelechatDate for today if there is not one already, but we probably also ought to put a unique constraint on TelechatDate.date if we mean for that to be unique.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I don't think a unique constraint will work - there are periods where a document can be scheduled for more than one telechat in practice. Fixing the generator is the right thing to do. Also look for opportunities to reduce the number of things happening in make_immutable_test_data especially if only one test (or a small number) uses what's set up. Instead, move the building into using factories for that small number of tests.

**Comment by jennifer-richards** [comment]
If there can actually be multiple telechats on a single day, we have a bug at least here: https://github.com/ietf-tools/datatracker/blob/main/ietf/iesg/agenda.py#L31

**Comment by rjsparks** [comment]
mmph - I was thinking about the wrong relationship - at the moment, we do not support having two telechats on the same day.
