### ISSUE TITLE
Submission status page should give a clear, detailed error after async validation fails

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5696]
### Describe the issue

If a submission fails validation in a way that prevents metadata extraction (e.g., due to a title mismatch as in #5691), the submission status page shows a lot of loud warnings about metadata problems. These are irrelevant because the metadata simply weren't populated. Worse, they distract from the event history at the bottom of the page which has the only hint at what specifically went wrong.

This needs to be cleaned up to show only relevant information and, ideally, to more emphatically describe why the draft was rejected.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

---
Aggregated with agent assistance on 2026-08-18

**Comment by jennifer-richards** [comment]
Kind of a special case of #4346

**Comment by jennifer-richards** [comment]
Another special case that triggered this was a draft containing SVG artwork including the `x` attribute on the `<svg>` element. As I understand it, this is not allowed by the RFC SVG schema. The result is this bug being triggered. The backend logs show a more helpful message that should be relayed to the user:
```
ietf/submit/utils.py(1328) in process_and_validate_submission(): Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2183, in validate
        self.v3_rng.assertValid(tree)
    File "src/lxml/etree.pyx", line 3643, in lxml.etree._Validator.assertValid
        lxml.etree.DocumentInvalid: Invalid attribute x for element svg, line 675
```
and eventually the less specific (but still better than current)
```
xml2rfc.writers.base.RfcWriterError: [draft path removed]: Error: Invalid document before running preptool.
```

**Comment by jennifer-richards** [comment]
Yet another: a draft came in with `<artwork [...] src="art/something.ascii-art"></artwork>`. This resulted in no actual error message in the log, just a useless "see above" message. Running it through xml2rfc revealed errors about the src file not existing. From the user's perspective, again, the draft just failed.

**Comment by rjsparks** [comment]
```
 <rfc category="std" ipr="trust200902" consensus="true" submissionType="IETF" docName="draft-somebody-did-something-00.txt">
```
fails because of the .txt in docName, but the result on the UI is inscrutable.

**Comment by jennifer-richards** [comment]
A file failed submission because of the `version=""` in the header. This is accepted without comment by xml2rfc, but causes the following error in the celery logs:
```
[2023-08-22 07:09:25,002: WARNING/ForkPoolWorker-2]     ietf/submit/utils.py(1328) in process_and_validate_submission(): Traceback (most recent call last):
  File "/workspace/ietf/submit/utils.py", line 1266, in process_and_validate_submission
    render_missing_formats(submission)  # makes HTML and text, unless text was uploaded
  File "/workspace/ietf/submit/utils.py", line 948, in render_missing_formats
    xmltree.tree = prep.prep()
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/preptool.py", line 219, in prep
    tree = self.dispatch(self.selectors)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1925, in dispatch
    func(e, e.getparent())
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2158, in validate_before
    self.die(self.root, 'Expected <rfc> version="3", but found "%s"' % version)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1837, in die
    raise RfcWriterError(msg)
xml2rfc.writers.base.RfcWriterError: /a/www/www6s/staging/draft-thomy-json-ntv-00.xml(12): Error: Expected <rfc> version="3", but found "0"
```
Changing the attribute to `version="3"` also causes it to fail, this time with 
```
[2023-08-22 07:11:03,164: WARNING/ForkPoolWorker-2]     ietf/submit/utils.py(1328) in process_and_validate_submission(): Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2121, in validate
    self.v3_rng.assertValid(tree)
  File "src/lxml/etree.pyx", line 3643, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Did not expect text in element rfc content, line 12
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/workspace/ietf/submit/utils.py", line 1266, in process_and_validate_submission
    render_missing_formats(submission)  # makes HTML and text, unless text was uploaded
  File "/workspace/ietf/submit/utils.py", line 948, in render_missing_formats
    xmltree.tree = prep.prep()
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/preptool.py", line 219, in prep
    tree = self.dispatch(self.selectors)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1925, in dispatch
    func(e, e.getparent())
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2159, in validate_before
    if not self.validate('before'):
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/preptool.py", line 173, in validate
    return super(PrepToolWriter, self).validate(when='%s running preptool'%when, warn=warn)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2153, in validate
    self.die(self.root, 'Invalid document%s.' % (when, ))
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1837, in die
    raise RfcWriterError(msg)
xml2rfc.writers.base.RfcWriterError: /a/www/www6s/staging/draft-thomy-json-ntv-00.xml(12): Error: Invalid document before running preptool.
```
Changing the attribute to `version="2"` fixes the problem (and presumably is the correct value for the structure of the XML).

**Comment by jennifer-richards** [comment]
As noted on #6221, that PR improves the status page to be less confusing after an error occurred but we should do a better job actually handling the errors we've gathered here before we close this.

**Comment by rjsparks** [comment]
It would be good to be more transparent about what the failures actually _were_.

**Comment by jennifer-richards** [comment]
> It would be good to be more transparent about what the failures actually _were_.

Yes. There's some existing code that grabs exception messages and logs them in the event history. If we can get the actual errors into those event description we'll be almost there. The failures here are hitting generic handling. I'm hoping we can do this in a way that doesn't turn into a lot of special cases...

**Comment by jennifer-richards** [comment]
#6158 related item that should be reflected clearly on the submission status page.

I've renamed this ticket to be more specific about what it's evolved to track.

**Comment by jennifer-richards** [comment]
#7107 is another case that should be addressed
