### ISSUE TITLE
Transient test failures

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#5834]
We have some transient test failures creeping back in. This issue will gather them.

**Comment by rjsparks** [comment]
======================================================================

FAIL: test_edit (ietf.secr.sreq.tests.SessionRequestTestCase.test_edit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/secr/sreq/tests.py", line 160, in test_edit
    self.assertFalse(sessions[0].joint_with_groups.count())
AssertionError: 2 is not false

----------------------------------------------------------------------

**Comment by larseggert** [comment]
I just hit the above as well.

**Comment by rjsparks** [comment]
======================================================================
FAIL: test_review_requests (ietf.group.tests_review.ReviewTests.test_review_requests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/ietf/group/tests_review.py", line 44, in test_review_requests
    self.assertContains(r, assignment.reviewer.person.name)
  File "/home/dev/.local/lib/python3.9/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'Bjorn van 't Wel' in response

**Comment by larseggert** [comment]
@rjsparks the `ietf.group.tests_review.ReviewTests.test_review_requests` failure shoule be fixed by #5986. The issue was that the `'` got HTML-escaped to `&#x27;`.

**Comment by rjsparks** [comment]
Makes me wonder - Do we have an open path already (and does this make it any worse) for arbitrary HTML injection through the user provided name? Maybe this needs bleaching before being marked clean on the way out?

**Comment by larseggert** [comment]
Possibly. The other way to fix this is of course to not mark it safe and instead compare against the escaped name in the test.

**Comment by larseggert** [comment]
@rjsparks Which fix do you prefer?

**Comment by jennifer-richards** [comment]
Better not to mark it safe unless we actually mean to allow literal HTML in the fields - I'm fairly sure we want Django to do the escaping here and we should update the tests to expect that.

**Comment by larseggert** [comment]
Ok. Will update the PR at the code sprint

**Comment by larseggert** [comment]
Done

**Comment by larseggert** [comment]
Here is another:
```
======================================================================
FAIL: test_edit (ietf.secr.sreq.tests.SessionRequestTestCase.test_edit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/secr/sreq/tests.py", line 168, in test_edit
    self.assertContains(r, 'Second session with: {} {}'.format(group3.acronym, group4.acronym))
  File "/usr/local/lib/python3.9/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'Second session with: acronym5258 acronym5260' in response
```

**Comment by larseggert** [comment]
Same error as above in this run: https://github.com/ietf-tools/datatracker/actions/runs/5902988978/job/16012002249
```
======================================================================
FAIL: test_edit (ietf.secr.sreq.tests.SessionRequestTestCase.test_edit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/secr/sreq/tests.py", line 168, in test_edit
    self.assertContains(r, 'Second session with: {} {}'.format(group3.acronym, group4.acronym))
  File "/usr/local/lib/python3.9/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'Second session with: acronym5270 acronym5272' in response
```

**Comment by larseggert** [comment]
`ietf.secr.sreq.tests.SessionRequestTestCase.test_edit` was fixed in #6394

**Comment by jennifer-richards** [comment]
```
FAIL: test_upcoming_view_filter_whitespace (ietf.meeting.tests_js.InterimTests) 
Whitespace in filter lists should be ignored 
---------------------------------------------------------------------- 
Traceback (most recent call last): 
 File "/__w/datatracker/datatracker/ietf/meeting/tests_js.py", line 1195, in test_upcoming_view_filter_whitespace 
 self.do_upcoming_view_filter_test('?show=mars , ames &hide= ames', self.displayed_interims(groups=['mars'])) 
 File "/__w/datatracker/datatracker/ietf/meeting/tests_js.py", line 1048, in do_upcoming_view_filter_test 
 self.assert_upcoming_meeting_visibility(visible_meetings) 
 File "/__w/datatracker/datatracker/ietf/meeting/tests_js.py", line 1003, in assert_upcoming_meeting_visibility 
 self.assertEqual(unexpected, set(), "Unexpected row visible") 
AssertionError: Items in the first set but not the second: 
'interim-2023-sg-01' : Unexpected row visible
```
(also randomly affects other tests using the same helper method)

**Comment by rjsparks** [comment]
```
 ======================================================================
FAIL: test_complete_review_upload_content (ietf.doc.tests_review.ReviewTests.test_complete_review_upload_content)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/doc/tests_review.py", line 838, in test_complete_review_upload_content
    self.assertIn(assignment.reviewer.role_set.filter(group=assignment.review_request.team,name='reviewer').first().person.plain_name(), parseaddr(outbox[0]["From"])[0] )
AssertionError: 'எழில்மன்னன் தங்கராஐ;' not found in 'எழில்மன்னன் via Datatracker'
```

**Comment by rjsparks** [comment]
`======================================================================
FAIL: test_session_attendance (ietf.meeting.tests_views.ProceedingsTests.test_session_attendance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/meeting/tests_views.py", line 8601, in test_session_attendance
    self.assertContains(r, person.name)
  File "/usr/local/lib/python3.9/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'Arthur da Mata' in response`

**Comment by rjsparks** [comment]
```
 ======================================================================
FAIL: test_session_attendance (ietf.meeting.tests_views.ProceedingsTests.test_session_attendance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/meeting/tests_views.py", line 8853, in test_session_attendance
    self.assertContains(r, person.plain_name())
  File "/usr/local/lib/python3.9/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'Wayne O'Neill' in response
```

**Comment by Creatur3245** [comment]
Python:

def test_session_attendance(self):
    self.assertEqual(r.status_code, 200)  
    self.assertContains(r, '3 attendees')
    for person in persons:
        # Ensure plain_name() is correctly rendered
        self.assertContains(r, person.plain_name())

    # Test for the "I was there" button.
    def _test_button(person, expected):
        # attempt to POST anyway is ignored
        r = self.client.post(attendance_url)
        self.assertEqual(r.status_code, 200)
        self.assertNotContains(r, persons[3].plain_name())
        self.assertEqual(session.attended_set.count(), 3)
        # button is shown, and POST is accepted
        meeting.importantdate_set.update(name_id='revsub', date=date_today() + datetime.timedelta(days=20))
        _test_button(persons[3], True)
        r = self.client.post(attendance_url)
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, persons[3].plain_name())
        self.assertEqual(session.attended_set.count(), 4)

    # When the meeting is finalized, a bluesheet file is generated,
    text = doc.text()
    self.assertIn('4 attendees', text)
    for person in persons:
        # Ensure plain_name() is correctly rendered in document text
        self.assertIn(person.plain_name(), text)
    r = self.client.get(session_url)
    self.assertContains(r, doc.get_href())
    self.assertNotContains(r, attendance_url)

**Comment by rjsparks** [comment]
```
 ======================================================================
FAIL: test_rfc_index (ietf.sync.tests.RFCSyncTests.test_rfc_index)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/sync/tests.py", line 463, in test_rfc_index
    self.assertIn("set pages to 42", rfc_events[0].desc)
AssertionError: 'set pages to 42' not found in "Received changes through RFC Editor sync (created document RFC 1234, created became rfc relationship between draft-bogusperson-acronym7755-musings3293 and RFC 1234, set title to 'A Testing RFC', set abstract to 'This is some interesting text.', set standardization level to Proposed Standard, added RFC published event at 2025-05-14, created updates relation between RFC 1234 and RFC 123, added Errata tag)"

----------------------------------------------------------------------
Ran 1589 tests in 1380.595s
```

**Comment by rjsparks** [comment]
```
FAIL: test_normal_schedule (ietf.meeting.tests_schedule_generator.ScheduleGeneratorTest.test_normal_schedule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/ietf/meeting/tests_schedule_generator.py", line 83, in test_normal_schedule
    self.assertIn('scheduling 13 sessions in 20 timeslots', output)
AssertionError: 'scheduling 13 sessions in 20 timeslots' not found in '\nRunning automatic schedule layout for meeting IETF 205\n\nWARNING: session wg2 (pk 177) has no attendees set, assuming any room fits== Initial scheduler starting, scheduling 13 sessions in 26 timeslots ==Scheduled wg1 at 2020-06-02 02:00:00+00:00 in location 397Scheduled wg2 at 2020-06-01 23:00:00+00:00 in location 396Scheduled bof1 at 2020-06-01 01:00:00+00:00 in location 396Scheduled bof1 at 2020-06-02 22:00:00+00:00 in location 397Scheduled wg2 at 2020-06-01 00:00:00+00:00 in location 396Scheduled wg2 at 2020-06-03 02:00:00+00:00 in location 397Scheduled wg2 at 2020-06-01 22:00:00+00:00 in location 397Scheduled bof2 at 2020-06-03 01:00:00+00:00 in location 396Scheduled bof2 at 2020-06-01 23:00:00+00:00 in location 397Scheduled area1 at 2020-06-02 01:00:00+00:00 in location 397Scheduled prg1 at 2020-06-01 02:00:00+00:00 in location 397Scheduled wg3 at 2020-06-02 23:00:00+00:00 in location 397Scheduled area2 at 2020-06-02 00:00:00+00:00 in location 397Initial schedule completed with 2 violations, total cost 200,000, in 0m 0.01s== Optimiser starting run 1, dynamic cost after last run None ==Dynamic violations in last optimiser run: []Optimiser found an optimal scheduleOptimisation completed with 2 violations, cost 200,000, 1 runs in 0m 0.00sRemaining violations:No timeslot with sufficient duration available for wg2, requested 2:00:00, trimmed to 1:00:00No timeslot with sufficient capacity available for wg2, requested 500, trimmed to 100Schedule saved as auto-205-00'

----------------------------------------------------------------------
```

**Comment by rjsparks** [comment]
```
======================================================================
FAIL: test_session_attendance (ietf.meeting.tests_views.ProceedingsTests.test_session_attendance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/meeting/tests_views.py", line 9323, in test_session_attendance
    self.assertContains(r, person.plain_name())
  File "/usr/local/lib/python3.9/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'David O'Connor' in response
```

**Comment by jennifer-richards** [comment]
```
======================================================================
FAIL: run_template_validation (ietf.utils.test_runner.TemplateValidationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/utils/test_runner.py", line 357, in run_template_validation
    self.validate_html.validate(self)
  File "/__w/datatracker/datatracker/ietf/utils/test_runner.py", line 1080, in validate
    testcase.fail('\n'.join(errors))
AssertionError: 
/tmp/html-validate-0wi6cdlz/5c44c9cb6c1f72c6/ietf/templates/nomcom/view_feedback.html:
                    </tr>
                
                    <tr>
                        <td>
                            <a href="/nomcom/2047/private/view-feedback/nominee/66">
                             ^
                             wcag/h30: Anchor link must have a text describing its purpose on line 845:30
                                
                            </a>
                        </td>
                        <td>
                            <a href="/nomcom/2047/private/view-feedback/nominee/66">

[... snip ...]
```

**Comment by rjsparks** [comment]
```
 ======================================================================
FAIL: test_requests_history_filter_page (ietf.group.tests_review.RequestsHistoryTests.test_requests_history_filter_page)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/group/tests_review.py", line 913, in test_requests_history_filter_page
    self.assertNotContains(r, 'Ready')
  File "/usr/local/lib/python3.12/site-packages/django/test/testcases.py", line 676, in assertNotContains
    self.assertEqual(
AssertionError: 2 != 0 : Response should not contain 'Ready'

----------------------------------------------------------------------
```

**Comment by rjsparks** [comment]
```
 ======================================================================
FAIL: test_session_attendance (ietf.meeting.tests_views.ProceedingsTests.test_session_attendance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/datatracker/datatracker/ietf/meeting/tests_views.py", line 9335, in test_session_attendance
    self.assertContains(r, person.plain_name())
  File "/usr/local/lib/python3.12/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find 'Sean O'Hickey' in response
```

**Comment by rjsparks** [comment]
Closing this issue - the only unaddressed anecdote above is in the playwright tests which are being revisited.
Future transients should be captured as their own issue using the `transient test failure` label.
