### ISSUE TITLE
Problem handling version attribute on rfc element of xml submissions

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6183]
### Describe the issue

Handling of the `version` attribute of the `<rfc>` element is causing I-D submissions to be rejected even in cases where xml2rfc handles the file without a problem. This was the cause of the failure in #6172 and was noted in https://github.com/ietf-tools/datatracker/issues/5696#issuecomment-1688294452 and elsewhere in that ticket.

Need to investigate why this is failing, particularly for the cases where `version` is `"0"` or `""`. The `"3"` case is legitimately invalid for the draft in question - it causes xml2rfc to reject the draft with an error. In that case, the only problem is the broader issue already captured by #5696.

A file failed submission because of`version=""` in the`<rfc...>` element. This is accepted without comment by xml2rfc, but causes the following error in the celery logs:
```
[2023-08-22 07:09:25,002: WARNING/ForkPoolWorker-2]     ietf/submit/utils.py(1328) in process_and_validate_submission(): Traceback (most recent call last):
  File "/workspace/ietf/submit/utils.py", line 1266, in process_and_validate_submission
    render_missing_formats(submission)  # makes HTML and text, unless text was uploaded
  File "/workspace/ietf/submit/utils.py", line 948, in render_missing_formats
    xmltree.tree = prep.prep()
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/preptool.py", line 219, in prep
    tree = self.dispatch(self.selectors)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1925, in dispatch
    func(e, e.getparent())
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2158, in validate_before
    self.die(self.root, 'Expected <rfc> version="3", but found "%s"' % version)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1837, in die
    raise RfcWriterError(msg)
xml2rfc.writers.base.RfcWriterError: /a/www/www6s/staging/draft-thomy-json-ntv-00.xml(12): Error: Expected <rfc> version="3", but found "0"
```
Changing the attribute to `version="3"` also causes it to fail, this time with 
```
[2023-08-22 07:11:03,164: WARNING/ForkPoolWorker-2]     ietf/submit/utils.py(1328) in process_and_validate_submission(): Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2121, in validate
    self.v3_rng.assertValid(tree)
  File "src/lxml/etree.pyx", line 3643, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Did not expect text in element rfc content, line 12
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/workspace/ietf/submit/utils.py", line 1266, in process_and_validate_submission
    render_missing_formats(submission)  # makes HTML and text, unless text was uploaded
  File "/workspace/ietf/submit/utils.py", line 948, in render_missing_formats
    xmltree.tree = prep.prep()
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/preptool.py", line 219, in prep
    tree = self.dispatch(self.selectors)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1925, in dispatch
    func(e, e.getparent())
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2159, in validate_before
    if not self.validate('before'):
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/preptool.py", line 173, in validate
    return super(PrepToolWriter, self).validate(when='%s running preptool'%when, warn=warn)
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 2153, in validate
    self.die(self.root, 'Invalid document%s.' % (when, ))
  File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/base.py", line 1837, in die
    raise RfcWriterError(msg)
xml2rfc.writers.base.RfcWriterError: /a/www/www6s/staging/draft-thomy-json-ntv-00.xml(12): Error: Invalid document before running preptool.
```
Changing the attribute to `version="2"` fixes the problem (and presumably is the correct value for the structure of the XML).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

---
Aggregated with agent assistance on 2026-08-18

**Comment by loco-philippe** [comment]
The rfc attribute `version="2"` is  indicated in the RFCXML vocabulary reference

![Capture d’écran 2023-08-22 233820](https://github.com/ietf-tools/datatracker/assets/92333742/905b688e-cdf7-4ad3-9915-a7afb1666621).
It will be consistent to add this value in the XML templates (resource "Templates and schemas")

**Comment by jennifer-richards** [comment]
> The rfc attribute `version="2"` is indicated in the RFCXML vocabulary reference
> 
>  It will be consistent to add this value in the XML templates (resource "Templates and schemas")

Do you mean `version="3"`? That's what's expected in the vocabulary reference because it documents the v3 vocabulary.

The templates I checked (the ones at the top of https://authors.ietf.org/en/templates-and-schemas) all have `version="3"`). Are there any places that `version=""` is being encouraged?

**Comment by loco-philippe** [comment]
> > The rfc attribute `version="2"` is indicated in the RFCXML vocabulary reference
> > It will be consistent to add this value in the XML templates (resource "Templates and schemas")
> 
> Do you mean `version="3"`? That's what's expected in the vocabulary reference because it documents the v3 vocabulary.
> 
> The templates I checked (the ones at the top of https://authors.ietf.org/en/templates-and-schemas) all have `version="3"`). Are there any places that `version=""` is being encouraged?

My previous comment is totaly wrong !!!!

You are right:
- the attribute indicated in the RFCXML is `version="3"` and not `version="2"` !!
- the templates are effectively consistent with this value  !!

I think a little rest is needed....
