### ISSUE TITLE
`--no-validate-html` and `--skip-coverage` together break test

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6421]
### Describe the issue

```dev ➜ /workspace $ ietf/manage.py test --settings=settings_test --no-validate-html --skip-coverage
     Datatracker 11.0.0-dev test suite, 03 October 2023 01:14:35 PDT:
     Python 3.9.16 (main, Apr 12 2023, 12:03:39)  [GCC 10.2.1 20210110].
     Django 4.2.5, settings 'settings_test'
     Changing TEMPLATES[0]['OPTIONS']['string_if_invalid'] to '' during testing
     Changing INTERNAL_IPS to '[]' during testing.
     Running an SMTP test server on 127.0.0.1:2026 to catch outgoing email.
     Loading factory-boy random state from .factoryboy_random_state
     Not validating any generated HTML; please do so at least once before committing changes
Traceback (most recent call last):
  File "/workspace/ietf/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/commands/test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
  File "/workspace/ietf/utils/test_runner.py", line 1145, in run_tests
    failures = super(IetfTestRunner, self).run_tests(test_labels, extra_tests=extra_tests, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/test/runner.py", line 1048, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/workspace/ietf/utils/test_runner.py", line 1083, in build_suite
    return super().build_suite(test_labels, extra_tests, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/test/runner.py", line 899, in build_suite
    all_tests.extend(iter_test_cases(tests))
  File "/home/dev/.local/lib/python3.9/site-packages/django/test/utils.py", line 260, in iter_test_cases
    for test in tests:
TypeError: 'NoneType' object is not iterable
```
Removing either `--no-validate-html` or `--skip-coverage` makes the test run start.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
We could look at this at the codesprint?
