### ISSUE TITLE
Datatracker fails without informative error message on draft submission

### ISSUE THREAD

**Issue by kesara** [ietf-tools/datatracker#7107]
### Describe the issue

When draft `front > date` only has a `year` attribute and the `year` is not the current year,
Example:
```
<rfc ..>
 <front>
  ...
  <date year="2023">
  ...
```

Datatracker fails with an error message:
```Submission rejected: A system error occurred while processing the submission.```

Under the hood code fails with following logs:
```
[2024-02-26 14:10:34,872: WARNING/ForkPoolWorker-2]     ietf/submit/utils.py(1327) in process_and_validate_submission(): Traceback (most recent call last):

  File "/workspace/ietf/submit/utils.py", line 1264, in process_and_validate_submission

    xml_metadata = process_submission_xml(submission.name, submission.rev)

  File "/workspace/ietf/submit/utils.py", line 1165, in process_submission_xml

    "document_date": xml_draft.get_creation_date(),

  File "/workspace/ietf/utils/xmldraft.py", line 165, in get_creation_date

    return self.parse_creation_date(self.xmlroot.find("front/date"))

  File "/workspace/ietf/utils/xmldraft.py", line 162, in parse_creation_date

    return datetime.date(year, month, day)

TypeError: an integer is required (got type NoneType)
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

---
Aggregated with agent assistance on 2026-08-18

**Comment by jennifer-richards** [comment]
We're collecting these over in #5696
