### ISSUE TITLE
Install bug 'ModuleNotFoundError: No module named 'ietf.settings_local''

### ISSUE THREAD

**Issue by holloway** [ietf-tools/datatracker#7437]
### Describe the issue

After following [the install docs](https://github.com/ietf-tools/datatracker?tab=readme-ov-file#the-tldr-to-get-going) it suggests running a test to verify the install,

```bash
ietf/manage.py test --settings=settings_test
```
which results in...

``` bash
Traceback (most recent call last):
  File "/workspace/ietf/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/base.py", line 404, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/base.py", line 367, in create_parser
    self.add_arguments(parser)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/commands/test.py", line 54, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/home/dev/.local/lib/python3.9/site-packages/django/test/utils.py", line 388, in get_runner
    test_runner_class = test_runner_class or settings.TEST_RUNNER
  File "/home/dev/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/dev/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dev/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/workspace/ietf/settings_test.py", line 13, in <module>
    from ietf.settings import *                                          # pyflakes:ignore
  File "/workspace/ietf/settings.py", line 1190, in <module>
    from ietf.settings_local import *            # pyflakes:ignore pylint: disable=wildcard-import
ModuleNotFoundError: No module named 'ietf.settings_local'
```

@kesara suggests that "looks like docker scripts aren't copying the file." (`ietf/settings_local.py` or similar)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Strange - your shell was in the app container? That should be getting a `settings_local.py` via https://github.com/ietf-tools/datatracker/blob/3d4482533322f49dc4b9c9b15660436749470dc8/docker/scripts/app-init.sh#L40-L46 which hasn't changed in a while. @NGPixel might know if it behaves differently in VSCode, though.

**Comment by NGPixel** [comment]
That was caused by the app-init.sh script not having write access to the project directory. Running a `chown -R $USER:$USER /workspace` then the app-init.sh fixes the issue.

**Comment by holloway** [comment]
Underlying cause for me was using Docker Desktop's version of Docker Compose while on Linux. The updated instructions to install Docker Compose manually fix this bug for me.

See https://github.com/ietf-tools/datatracker/commit/f01ef0c9157988cf62e625da0cad06cb7ddb631a
