### ISSUE TITLE
Install bug 'No such file or directory: '/workspace/ietf/../release-coverage.json''

### ISSUE THREAD

**Issue by holloway** [ietf-tools/datatracker#7439]
### Describe the issue

After following [the install docs](https://github.com/ietf-tools/datatracker?tab=readme-ov-file#the-tldr-to-get-going) it suggests running a test to verify the install,

```bash
ietf/manage.py test --settings=settings_test
```

which results in...

```
     Datatracker -dev test suite, 19 May 2024 15:49:21 PDT:
     Python 3.9.19 (main, May 14 2024, 09:05:28)  [GCC 10.2.1 20210110].
     Django 4.2.13, settings 'settings_test'
Traceback (most recent call last):
  File "/workspace/ietf/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/dev/.local/lib/python3.9/site-packages/django/core/management/commands/test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
  File "/workspace/ietf/utils/test_runner.py", line 1149, in run_tests
    failures = super(IetfTestRunner, self).run_tests(test_labels, extra_tests=extra_tests, **kwargs)
  File "/home/dev/.local/lib/python3.9/site-packages/django/test/runner.py", line 1047, in run_tests
    self.setup_test_environment()
  File "/workspace/ietf/utils/test_runner.py", line 777, in setup_test_environment
    with io.open(self.coverage_file, encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/ietf/../release-coverage.json'
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
Puzzled on this one - with a fresh checkout, I get:
```
dev ➜ /workspace $ ietf/manage.py test --settings=settings_test
     Datatracker -dev test suite, 22 May 2024 08:01:29 PDT:
     Python 3.9.19 (main, May 14 2024, 07:14:34)  [GCC 10.2.1 20210110].
     Django 4.2.13, settings 'settings_test'
     Changing TEMPLATES[0]['OPTIONS']['string_if_invalid'] to '' during testing
     Changing INTERNAL_IPS to '[]' during testing.
     Running an SMTP test server on 127.0.0.1:2026 to catch outgoing email.
     Saving factory-boy random state to .factoryboy_random_state
     Validating all HTML generated during the tests
     Skipping selenium tests: 'geckodriver' executable not found.
Found 1521 test(s).
     Creating test database...
     Loading global test fixtures: names, ietf.utils.test_data.make_immutable_base_data, nomcom_templates, proceedings_templates
System check identified no issues (3 silenced).
```
followed by the tests running as normal. This is not in VSCode, though, so it may be different in the devcontainer.

**Comment by NGPixel** [comment]
Same root cause as #7437

**Comment by holloway** [comment]
Underlying cause for me was using Docker Desktop's version of Docker Compose while on Linux. The updated instructions to install Docker Compose manually fix this bug for me.

See https://github.com/ietf-tools/datatracker/commit/f01ef0c9157988cf62e625da0cad06cb7ddb631a
